### PR TITLE
Manual merge-conflict resolution for May 6

### PR DESCRIPTION
**Pull request by j6k4m8**
Fixes the merge-conflict in #27 . Unfortunately, looks like I can't push to that branch myself without some extra accesses.

I think we can merge this one, close that one, and we're back on track.

### CODE REVIEW

**Comment by j6k4m8** [comment]
Can I get a review here so we can merge this (and close #27)?

**Review by movestill — APPROVED** [review]
Approved based on just looking at the changes you made to the original PR.

**Review by hannah-martinez — APPROVED** [review]
Looks like there are some significant UI changes in the way a user interacts with the segmentation and annotation tools. I'll approve because the code looks good, but I'm interested to see what the design looks like. I will 👀 when it's deployed

**Review by dxenes1 — APPROVED** [review]
LGTM!

**Pull request merged**
