### PR TITLE
Hannah/sync fork

### PR DESCRIPTION
**Pull request by hannah-martinez**
With this MR, we bring the current version of Google's neuroglancer (https://github.com/google/neuroglancer) into the JHUAPL-Boss version, and update the code in `/src/neuroglancer/datasource/boss` to work correctly with it.

To run locally, pull this branch and do:
```
npm install
npm run dev-server
```
Then navigate to `localhost:8080` in the browser. Please try loading and testing with datasets which have a `boss://` prefix - those will be best for isolating bugs.
I've also created some links with datasets included:
[Morgan](http://localhost:8080/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B100018%2C99952%2C5018.5%5D%2C%22crossSectionScale%22:1%2C%22projectionOrientation%22:%5B-0.2573384642601013%2C-0.31606724858283997%2C0.033762406557798386%2C0.9125450849533081%5D%2C%22projectionScale%22:749.7027714096746%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22boss://https://api.bossdb.io/morgan2020/lgn/em%22%2C%22name%22:%22lgn%22%7D%5D%2C%22layout%22:%224panel%22%7D)  
[Kasthuri](http://localhost:8080/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-9%2C%22m%22%5D%2C%22y%22:%5B4e-9%2C%22m%22%5D%2C%22z%22:%5B4e-8%2C%22m%22%5D%7D%2C%22position%22:%5B7753.12646484375%2C12465.4228515625%2C919%5D%2C%22crossSectionScale%22:6.564900377979953%2C%22projectionScale%22:2071.067811865475%2C%22layers%22:%5B%7B%22type%22:%22image%22%2C%22source%22:%22boss://https://api.bossdb.io/kasthuri2015/em/cc%22%2C%22name%22:%22Kasthuri2015%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22boss://https://api.bossdb.io/kasthuri2015/em/3cylneuron_v1%22%2C%22name%22:%223cylneuron_v1%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%22boss://https://api.bossdb.io/kasthuri2015/em/3cylsynapse_v1%22%2C%22name%22:%223cylsynapse_v1%22%7D%5D%2C%22showSlices%22:false%2C%22layout%22:%22xy%22%7D)

When reviewing, the files I worked in to resolve merge conflicts and fix runtime errors should receive special attention:
* all of the `/src/neuroglancer/datasource/boss` folder, and especially `frontend.js`
* `package.json`
* `/config` now uses esbuild instead of webpack
* `/.github` contains new github actions

A wiki page will be coming soon with a list of features that the new neuroglancer version provides for us. I will post it in Slack as soon as it's finished.

### CODE REVIEW

**Review by j6k4m8 — APPROVED** [review]
Did a light-speed review here — this looks good to me, in light of local debug/test sessions :)

**Comment by movestill** [comment]
> Did a light-speed review here — this looks good to me, in light of local debug/test sessions :)

@j6k4m8 Did you test that special dataset that has the native resolution offset?

**Comment by hannah-martinez** [comment]
Adding a link to a wiki page I made. Feel free to read through - it may prove helpful for reviewing.
https://github.com/aplbrain/wiki/tree/master/projects/neuroglancer

**Comment by j6k4m8** [comment]
@movestill I did indeed, and we're looking good 😎

**Review by dxenes1 — APPROVED** [review]
Worked for me on local tests on api.bossdb.io. However couldn't test on my dev stack due to a key-cloak issue, but thats something we should probably fix in the backend.

**Pull request merged**
